[project]
name = "email-classifier"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=1.2.0",
    "numpy>=2.4.0",
    "openai>=2.14.0",
    "pandas>=2.3.3",
]
